# Generated by Django 3.2.8 on 2021-10-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0004_increase_max_char_length_status'),
    ]

    operations = [
         migrations.RenameModel('ExpressCheckoutTransaction', 'CheckoutTransaction')
    ]
